language: python
dist: xenial
python:
  - "3.7"
env:
  - TOX_ENV=py27-django1.11
  - TOX_ENV=py37-django1.11
  - TOX_ENV=py37-django2.2
install:
  - pip install tox
notifications:
  email:
    - jason.ward@policystat.com
script: tox -e $TOX_ENV
